sudo: true
dist: trusty
language: emacs-lisp
env:
  matrix:
    - EMACS=emacs24
    - EMACS=emacs25
    - EMACS=emacs-snapshot

before_install:
  - sudo apt-add-repository -y ppa:adrozdoff/emacs
  - sudo add-apt-repository -y ppa:ubuntu-elisp
  - sudo apt-get update -qq
  - sudo apt-get install -qq $EMACS
  - git clone --recursive git://github.com/apiaryio/drafter.git
  - cd drafter && ./configure && make && sudo make install && cd ..

script:
  - make
