sudo: true
dist: precise
language: emacs-lisp
env:
  matrix:
    - emacs=emacs24
    - emacs=emacs-snapshot

before_install:
  - sudo add-apt-repository -y ppa:cassou/emacs
  - sudo add-apt-repository -y ppa:ubuntu-elisp
  - sudo apt-get update -qq
  - sudo apt-get install -qq $emacs
  - git clone --recursive git://github.com/apiaryio/drafter.git
  - cd drafter && ./configure && make && sudo make install && cd ..

script:
  - make
